In [123]:
import pandas as pd

base = pd.read_csv("dados_transacoes (2).csv")

df = pd.read_csv("dados_transacoes (2).csv")

df.head()

,id_cliente,data_transação,categoria_produto,idade,genero,preco,quantidade
0,fb3e7183-2f2b-49f0-b6fc-7bb82f62ab66,01/01/2024,Eletrônicos,56,Masculino,3077.35,1
1,554138dc-b472-4420-9e50-46fe24262598,11/01/2024,Eletrônicos,69,Masculino,3937.89,1
2,69361fcc-d6ea-44ed-9511-4d08cb5d5ec5,29/02/2024,Alimentos,46,Feminino,8.15,3
3,119a726d-e9f5-4ebc-bd72-c10e332182a0,10/04/2024,Roupas,32,Feminino,150.71,3
4,b48da9ae-f9a5-4866-a977-30571fc8496d,15/02/2024,Roupas,60,Feminino,103.89,4

In [124]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_cliente         50000 non-null  str
 1   data_transação     50000 non-null  str
 2   categoria_produto  50000 non-null  str
 3   idade              50000 non-null  int64
 4   genero             50000 non-null  str
 5   preco              50000 non-null  float64
 6   quantidade         50000 non-null  int64
dtypes: float64(1), int64(2), str(4)
memory usage: 2.7 MB

In [125]:


# loop for 

%timeit

for i in range(len(df)):
    df.loc[i,"total_for"] = df.loc[i, "quantidade"] * df.loc[i, "preco"]

In [126]:
df.head()

,id_cliente,data_transação,categoria_produto,idade,genero,preco,quantidade,total_for
0,fb3e7183-2f2b-49f0-b6fc-7bb82f62ab66,01/01/2024,Eletrônicos,56,Masculino,3077.35,1,3077.35
1,554138dc-b472-4420-9e50-46fe24262598,11/01/2024,Eletrônicos,69,Masculino,3937.89,1,3937.89
2,69361fcc-d6ea-44ed-9511-4d08cb5d5ec5,29/02/2024,Alimentos,46,Feminino,8.15,3,24.45
3,119a726d-e9f5-4ebc-bd72-c10e332182a0,10/04/2024,Roupas,32,Feminino,150.71,3,452.13
4,b48da9ae-f9a5-4866-a977-30571fc8496d,15/02/2024,Roupas,60,Feminino,103.89,4,415.56

In [127]:
df["total_apply"] = df.apply(
    lambda linha: linha["quantidade"] * linha["preco"],axis=1
)

df.head()

,id_cliente,data_transação,categoria_produto,idade,genero,preco,quantidade,total_for,total_apply
0,fb3e7183-2f2b-49f0-b6fc-7bb82f62ab66,01/01/2024,Eletrônicos,56,Masculino,3077.35,1,3077.35,3077.35
1,554138dc-b472-4420-9e50-46fe24262598,11/01/2024,Eletrônicos,69,Masculino,3937.89,1,3937.89,3937.89
2,69361fcc-d6ea-44ed-9511-4d08cb5d5ec5,29/02/2024,Alimentos,46,Feminino,8.15,3,24.45,24.45
3,119a726d-e9f5-4ebc-bd72-c10e332182a0,10/04/2024,Roupas,32,Feminino,150.71,3,452.13,452.13
4,b48da9ae-f9a5-4866-a977-30571fc8496d,15/02/2024,Roupas,60,Feminino,103.89,4,415.56,415.56

In [128]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_cliente         50000 non-null  str
 1   data_transação     50000 non-null  str
 2   categoria_produto  50000 non-null  str
 3   idade              50000 non-null  int64
 4   genero             50000 non-null  str
 5   preco              50000 non-null  float64
 6   quantidade         50000 non-null  int64
 7   total_for          50000 non-null  float64
 8   total_apply        50000 non-null  float64
dtypes: float64(3), int64(2), str(4)
memory usage: 3.4 MB

In [129]:
df["preco"]

0        3077.35
1        3937.89
2           8.15
3         150.71
4         103.89
          ...
49995    1223.14
49996      83.29
49997      85.85
49998    1482.96
49999      44.13
Name: preco, Length: 50000, dtype: float64

In [130]:
# operação vetorizada 

df["total_vetorizado"] = df["quantidade"] * df["preco"]

In [131]:
df["categoria_produto"].unique()

<StringArray>
['Eletrônicos', 'Alimentos', 'Roupas', 'Casa & Cozinha', 'Livros']
Length: 5, dtype: str

In [132]:
descontos_categorias = {
    "Eletronicos": 0.1,
    "Alimentos": 0.05,
    "Roupas":0.15,
    "Casa & Cozinha": 0.2,
    "Livros":0.25,
}

In [133]:
df["categoria_produto"].map(descontos_categorias)

0         NaN
1         NaN
2        0.05
3        0.15
4        0.15
         ...
49995    0.20
49996    0.25
49997    0.25
49998    0.20
49999    0.25
Name: categoria_produto, Length: 50000, dtype: float64

In [134]:
df["preco_desconto"] = df["preco"]*(1 - df["categoria_produto"].map(descontos_categorias))

In [135]:
df.head()

,id_cliente,data_transação,categoria_produto,idade,genero,preco,quantidade,total_for,total_apply,total_vetorizado,preco_desconto
0,fb3e7183-2f2b-49f0-b6fc-7bb82f62ab66,01/01/2024,Eletrônicos,56,Masculino,3077.35,1,3077.35,3077.35,3077.35,NaN
1,554138dc-b472-4420-9e50-46fe24262598,11/01/2024,Eletrônicos,69,Masculino,3937.89,1,3937.89,3937.89,3937.89,NaN
2,69361fcc-d6ea-44ed-9511-4d08cb5d5ec5,29/02/2024,Alimentos,46,Feminino,8.15,3,24.45,24.45,24.45,7.7425
3,119a726d-e9f5-4ebc-bd72-c10e332182a0,10/04/2024,Roupas,32,Feminino,150.71,3,452.13,452.13,452.13,128.1035
4,b48da9ae-f9a5-4866-a977-30571fc8496d,15/02/2024,Roupas,60,Feminino,103.89,4,415.56,415.56,415.56,88.3065