# `crosstab` do Pandas

Professor [Francisco Bustamante](https://linkedin.com/in/flsbustamante)

O `pandas.crosstab` é uma função que permite calcular tabelas de contingência (também conhecidas como tabelas cruzadas) que resumem a frequência de combinações de valores em duas ou mais colunas categóricas. Essa função é útil para explorar a relação entre diferentes categorias de dados, facilitando a visualização de como as categorias se distribuem e interagem.

Além da frequência (contagem), outras funções de agregação podem ser solicitadas.

Documentação: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.crosstab.html

Use o `pandas.crosstab` quando:

1. **Explorar relações categóricas**: Você quer explorar a relação entre duas ou mais variáveis categóricas, como a distribuição de vendas por região e produto, ou a frequência de respostas por faixa etária e gênero.
2. **Análise de dados**: Você precisa criar uma tabela de frequência para entender melhor como as diferentes categorias se comportam em conjunto.
3. **Preparação de dados para visualização**: Você está preparando dados para visualizações como gráficos de barras empilhadas, gráficos de calor ou outros tipos de gráficos que se beneficiam de tabelas de contigência.

Contexto:

Uma empresa que vende produtos em várias regiões. Cada produto pode ser vendido em várias regiões, e você tem um registro das vendas de cada produto em cada região para um determinado período. Você quer analisar a distribuição dessas vendas.

In [1]:
import pandas as pd

BASE = "./dados/produtos_regioes.csv"

df = pd.read_csv(BASE)

df

   produto        regiao  receita
0        A         Norte      100
1        B           Sul      150
2        C      Nordeste      200
3        A  Centro-Oeste      120
4        B       Sudeste      160
5        C           Sul      210
6        A  Centro-Oeste      130
7        B         Norte      170
8        C      Nordeste      220
9        A           Sul      140
10       A       Sudeste      110
11       B         Norte      155
12       C  Centro-Oeste      215
13       B           Sul      165
14       C         Norte      225
15       A       Sudeste      180
16       B      Nordeste      175
17       C           Sul      190
18       A  Centro-Oeste      160
19       B       Sudeste      155

In [2]:
# Calculando a tabela de contingência com contagens
pd.crosstab(df["regiao"], df["produto"])

produto       A  B  C
regiao
Centro-Oeste  3  0  1
Nordeste      0  1  2
Norte         1  2  1
Sudeste       2  2  0
Sul           1  2  2

In [3]:
pd.crosstab(df["regiao"], df["produto"], margins=True, margins_name="Vendas")

produto       A  B  C  Vendas
regiao
Centro-Oeste  3  0  1       4
Nordeste      0  1  2       3
Norte         1  2  1       4
Sudeste       2  2  0       4
Sul           1  2  2       5
Vendas        7  7  6      20

## Entendendo o normalize

In [4]:
pd.crosstab(
    df["regiao"], df["produto"], normalize=True, margins=True, margins_name="Total"
)

produto          A     B     C  Total
regiao
Centro-Oeste  0.15  0.00  0.05   0.20
Nordeste      0.00  0.05  0.10   0.15
Norte         0.05  0.10  0.05   0.20
Sudeste       0.10  0.10  0.00   0.20
Sul           0.05  0.10  0.10   0.25
Total         0.35  0.35  0.30   1.00

In [5]:
pd.crosstab(
    df["regiao"], df["produto"], normalize=True, margins=True, margins_name="Total"
).mul(100).round(1)

produto          A     B     C  Total
regiao
Centro-Oeste  15.0   0.0   5.0   20.0
Nordeste       0.0   5.0  10.0   15.0
Norte          5.0  10.0   5.0   20.0
Sudeste       10.0  10.0   0.0   20.0
Sul            5.0  10.0  10.0   25.0
Total         35.0  35.0  30.0  100.0

In [6]:
pd.crosstab(df["regiao"], df["produto"], margins=True, margins_name="Vendas")

produto       A  B  C  Vendas
regiao
Centro-Oeste  3  0  1       4
Nordeste      0  1  2       3
Norte         1  2  1       4
Sudeste       2  2  0       4
Sul           1  2  2       5
Vendas        7  7  6      20

In [7]:
pd.crosstab(
    df["regiao"], df["produto"], normalize="index", margins=True, margins_name="Total"
).mul(100).round(1)

produto          A     B     C
regiao
Centro-Oeste  75.0   0.0  25.0
Nordeste       0.0  33.3  66.7
Norte         25.0  50.0  25.0
Sudeste       50.0  50.0   0.0
Sul           20.0  40.0  40.0
Total         35.0  35.0  30.0

In [8]:
pd.crosstab(df["regiao"], df["produto"], margins=True, margins_name="Vendas")

produto       A  B  C  Vendas
regiao
Centro-Oeste  3  0  1       4
Nordeste      0  1  2       3
Norte         1  2  1       4
Sudeste       2  2  0       4
Sul           1  2  2       5
Vendas        7  7  6      20

In [9]:
pd.crosstab(
    df["regiao"], df["produto"], normalize="columns", margins=True, margins_name="Total"
).mul(100).round(1)

produto          A     B     C  Total
regiao
Centro-Oeste  42.9   0.0  16.7   20.0
Nordeste       0.0  14.3  33.3   15.0
Norte         14.3  28.6  16.7   20.0
Sudeste       28.6  28.6   0.0   20.0
Sul           14.3  28.6  33.3   25.0

## Usando outras funções de agregação

In [10]:
# agora vamos calcular a tabela de contingência com a receita total
pd.crosstab(
    df["regiao"],
    df["produto"],
    values=df["receita"],
    aggfunc="sum",
    margins=True,
    margins_name="Receita Total",
)

produto            A       B       C  Receita Total
regiao
Centro-Oeste   410.0     NaN   215.0            625
Nordeste         NaN   175.0   420.0            595
Norte          100.0   325.0   225.0            650
Sudeste        290.0   315.0     NaN            605
Sul            140.0   315.0   400.0            855
Receita Total  940.0  1130.0  1260.0           3330

In [11]:
# agora vamos calcular a tabela de contingência com a receita média
pd.crosstab(
    df["regiao"],
    df["produto"],
    values=df["receita"],
    aggfunc="mean",
    margins=True,
    margins_name="Receita Média",
).round(2)

produto             A       B      C  Receita Média
regiao
Centro-Oeste   136.67     NaN  215.0         156.25
Nordeste          NaN  175.00  210.0         198.33
Norte          100.00  162.50  225.0         162.50
Sudeste        145.00  157.50    NaN         151.25
Sul            140.00  157.50  200.0         171.00
Receita Média  134.29  161.43  210.0         166.50

In [12]:
pd.crosstab(
    df["regiao"],
    df["produto"],
    values=df["receita"],
    aggfunc="sum",
    normalize=True,
).mul(100).round(1)

produto          A    B     C
regiao
Centro-Oeste  12.3  0.0   6.5
Nordeste       0.0  5.3  12.6
Norte          3.0  9.8   6.8
Sudeste        8.7  9.5   0.0
Sul            4.2  9.5  12.0

In [13]:
pd.crosstab(
    df["regiao"],
    df["produto"],
    values=df["receita"],
    aggfunc="sum",
    normalize="index",
).mul(100).round(1)

produto          A     B     C
regiao
Centro-Oeste  65.6   0.0  34.4
Nordeste       0.0  29.4  70.6
Norte         15.4  50.0  34.6
Sudeste       47.9  52.1   0.0
Sul           16.4  36.8  46.8

In [14]:
pd.crosstab(
    df["regiao"],
    df["produto"],
    values=df["receita"],
    aggfunc="sum",
    normalize="columns",
).mul(100).round(1)

produto          A     B     C
regiao
Centro-Oeste  43.6   0.0  17.1
Nordeste       0.0  15.5  33.3
Norte         10.6  28.8  17.9
Sudeste       30.9  27.9   0.0
Sul           14.9  27.9  31.7

## Comparando com groupby

In [15]:
pd.crosstab(df["regiao"], df["produto"])

produto       A  B  C
regiao
Centro-Oeste  3  0  1
Nordeste      0  1  2
Norte         1  2  1
Sudeste       2  2  0
Sul           1  2  2

In [16]:
# obtendo a contagem igual ao crosstab mas com a função groupby
df.groupby(["regiao", "produto"]).count().rename(columns={"receita": "vendas"})

                      vendas
regiao       produto
Centro-Oeste A             3
             C             1
Nordeste     B             1
             C             2
Norte        A             1
             B             2
             C             1
Sudeste      A             2
             B             2
Sul          A             1
             B             2
             C             2

In [17]:
df.groupby(["regiao", "produto"]).count().unstack().fillna(0).rename(
    columns={"receita": "vendas"}
)

             vendas
produto           A    B    C
regiao
Centro-Oeste    3.0  0.0  1.0
Nordeste        0.0  1.0  2.0
Norte           1.0  2.0  1.0
Sudeste         2.0  2.0  0.0
Sul             1.0  2.0  2.0

In [18]:
pd.crosstab(
    df["regiao"],
    df["produto"],
    values=df["receita"],
    aggfunc="sum",
    margins=True,
    margins_name="Receita Total",
)

produto            A       B       C  Receita Total
regiao
Centro-Oeste   410.0     NaN   215.0            625
Nordeste         NaN   175.0   420.0            595
Norte          100.0   325.0   225.0            650
Sudeste        290.0   315.0     NaN            605
Sul            140.0   315.0   400.0            855
Receita Total  940.0  1130.0  1260.0           3330

In [19]:
# obtendo a soma igual ao crosstab mas com a função groupby
df.groupby(["regiao", "produto"]).sum().rename(columns={"receita": "receita_total"})

                      receita_total
regiao       produto
Centro-Oeste A                  410
             C                  215
Nordeste     B                  175
             C                  420
Norte        A                  100
             B                  325
             C                  225
Sudeste      A                  290
             B                  315
Sul          A                  140
             B                  315
             C                  400

In [20]:
df.groupby(["regiao", "produto"]).sum().unstack().fillna(0).rename(
    columns={"receita": "receita_total"}
)

             receita_total
produto                  A      B      C
regiao
Centro-Oeste         410.0    0.0  215.0
Nordeste               0.0  175.0  420.0
Norte                100.0  325.0  225.0
Sudeste              290.0  315.0    0.0
Sul                  140.0  315.0  400.0

### Comparação entre `crosstab` e `groupby`

Vantagens do `crosstab`:

- Simplicidade: `crosstab` é mais direto e simples de usar para criar tabelas de contingência.
- Automático: Ele lida automaticamente com os valores ausentes e adiciona margens (totais) de maneira conveniente.

Desvantagens do `crosstab`:

- Flexibilidade Limitada: Menos flexível que `groupby` para aplicar múltiplas agregações diferentes ou manipular dados de maneiras mais complexas.
- Personalização: Menos opções para personalizar a tabela resultante.

Vantagens do `groupby`:

- Flexibilidade: Muito mais flexível, permitindo aplicar múltiplas funções de agregação e manipular dados de várias maneiras.
- Versatilidade: Pode ser usado para uma ampla variedade de operações de agrupamento e agregação, não apenas para tabelas de contingência.

Desvantagens do `groupby`:

- Complexidade: Pode ser mais complexo e requer mais código para realizar operações simples que `crosstab` faz facilmente.
- Margens Manualmente: Adicionar margens (totais) requer operações adicionais, o que pode ser menos conveniente.

## Comparando com pivot_table

In [21]:
pd.crosstab(df["regiao"], df["produto"])

produto       A  B  C
regiao
Centro-Oeste  3  0  1
Nordeste      0  1  2
Norte         1  2  1
Sudeste       2  2  0
Sul           1  2  2

In [22]:
# o mesmo resultado pode ser obtido com a função pivot_table
df.pivot_table(
    index="regiao", columns="produto", values="receita", aggfunc="count", fill_value=0
)

produto       A  B  C
regiao
Centro-Oeste  3  0  1
Nordeste      0  1  2
Norte         1  2  1
Sudeste       2  2  0
Sul           1  2  2

In [23]:
pd.crosstab(
    df["regiao"],
    df["produto"],
    values=df["receita"],
    aggfunc="sum",
    margins=True,
    margins_name="Receita Total",
)

produto            A       B       C  Receita Total
regiao
Centro-Oeste   410.0     NaN   215.0            625
Nordeste         NaN   175.0   420.0            595
Norte          100.0   325.0   225.0            650
Sudeste        290.0   315.0     NaN            605
Sul            140.0   315.0   400.0            855
Receita Total  940.0  1130.0  1260.0           3330

In [24]:
# o mesmo resultado pode ser obtido com a função pivot_table
df.pivot_table(
    index="regiao",
    columns="produto",
    values="receita",
    aggfunc="sum",
    fill_value=0,
    margins=True,
    margins_name="Receita Total",
)

produto          A     B     C  Receita Total
regiao
Centro-Oeste   410     0   215            625
Nordeste         0   175   420            595
Norte          100   325   225            650
Sudeste        290   315     0            605
Sul            140   315   400            855
Receita Total  940  1130  1260           3330

### Comparação entre crosstab e pivot_table

Vantagens do `crosstab`:

- Simplicidade: `crosstab` é mais direto e simples de usar para criar tabelas de contingência.
- Automático: Ele lida automaticamente com valores ausentes e adiciona margens de maneira conveniente.
- Desempenho: Pode ser mais rápido e eficiente para grandes conjuntos de dados categóricos.

Desvantagens do `crosstab`:

- Flexibilidade Limitada: Menos flexível que `pivot_table` para aplicar múltiplas agregações diferentes ou manipular dados de maneiras mais complexas.
- Personalização: Menos opções para personalizar a tabela resultante.

Vantagens do `pivot_table`:

- Flexibilidade: Muito mais flexível, permitindo aplicar múltiplas funções de agregação e manipular dados de várias maneiras.
- Versatilidade: Pode ser usado para uma ampla variedade de operações de agrupamento e agregação, não apenas para tabelas de contingência.
- Suporte a Vários Agregadores: Pode aplicar múltiplas funções de agregação ao mesmo tempo, como `sum`, `mean`, `count`, etc.

Desvantagens do `pivot_table`:

- Complexidade: Pode ser mais complexo e requer mais código para realizar operações simples que `crosstab` faz facilmente.