In [369]:
import pandas as pd

df = pd.read_csv("produtos_regioes.csv")

df

   produto        regiao  receita
0        A         Norte      100
1        B           Sul      150
2        C      Nordeste      200
3        A  Centro-Oeste      120
4        B       Sudeste      160
5        C           Sul      210
6        A  Centro-Oeste      130
7        B         Norte      170
8        C      Nordeste      220
9        A           Sul      140
10       A       Sudeste      110
11       B         Norte      155
12       C  Centro-Oeste      215
13       B           Sul      165
14       C         Norte      225
15       A       Sudeste      180
16       B      Nordeste      175
17       C           Sul      190
18       A  Centro-Oeste      160
19       B       Sudeste      155

In [370]:
pd.crosstab(df["regiao"], df["produto"])

produto       A  B  C
regiao
Centro-Oeste  3  0  1
Nordeste      0  1  2
Norte         1  2  1
Sudeste       2  2  0
Sul           1  2  2

In [371]:
# margins é adicionar totais automáticos na tabela
# margins são os totais 
pd.crosstab(df["regiao"], df["produto"], margins=True)
pd.crosstab(df["regiao"], df["produto"], margins=True, margins_name="Vendas")

produto       A  B  C  Vendas
regiao
Centro-Oeste  3  0  1       4
Nordeste      0  1  2       3
Norte         1  2  1       4
Sudeste       2  2  0       4
Sul           1  2  2       5
Vendas        7  7  6      20

In [372]:
# normalize 
# normalizar 
# transforma contagens em porcentagens/proporções

pd.crosstab(df["regiao"], df["produto"],normalize=True, margins=True, margins_name="Total")

produto          A     B     C  Total
regiao
Centro-Oeste  0.15  0.00  0.05   0.20
Nordeste      0.00  0.05  0.10   0.15
Norte         0.05  0.10  0.05   0.20
Sudeste       0.10  0.10  0.00   0.20
Sul           0.05  0.10  0.10   0.25
Total         0.35  0.35  0.30   1.00

In [373]:
pd.crosstab(df["regiao"], df["produto"],normalize=True, margins=True, margins_name="Total")

produto          A     B     C  Total
regiao
Centro-Oeste  0.15  0.00  0.05   0.20
Nordeste      0.00  0.05  0.10   0.15
Norte         0.05  0.10  0.05   0.20
Sudeste       0.10  0.10  0.00   0.20
Sul           0.05  0.10  0.10   0.25
Total         0.35  0.35  0.30   1.00

In [374]:


pd.crosstab(df["regiao"], df["produto"],normalize=True, margins=True, margins_name="Total")

produto          A     B     C  Total
regiao
Centro-Oeste  0.15  0.00  0.05   0.20
Nordeste      0.00  0.05  0.10   0.15
Norte         0.05  0.10  0.05   0.20
Sudeste       0.10  0.10  0.00   0.20
Sul           0.05  0.10  0.10   0.25
Total         0.35  0.35  0.30   1.00

In [375]:
# usamos a multiplicação * vezes 100
pd.crosstab(
    df["regiao"], df["produto"],normalize=True, margins=True, margins_name="Total"
    )*100

produto          A     B     C  Total
regiao
Centro-Oeste  15.0   0.0   5.0   20.0
Nordeste       0.0   5.0  10.0   15.0
Norte          5.0  10.0   5.0   20.0
Sudeste       10.0  10.0   0.0   20.0
Sul            5.0  10.0  10.0   25.0
Total         35.0  35.0  30.0  100.0

In [376]:
pd.crosstab(
    df["regiao"], df["produto"],normalize="index", margins=True, margins_name="Total"
    ).mul(100).round(1)

produto          A     B     C
regiao
Centro-Oeste  75.0   0.0  25.0
Nordeste       0.0  33.3  66.7
Norte         25.0  50.0  25.0
Sudeste       50.0  50.0   0.0
Sul           20.0  40.0  40.0
Total         35.0  35.0  30.0

In [377]:
pd.crosstab(
    df["regiao"], df["produto"],normalize="columns", margins=True, margins_name="Total"
    ).mul(100).round(1)

produto          A     B     C  Total
regiao
Centro-Oeste  42.9   0.0  16.7   20.0
Nordeste       0.0  14.3  33.3   15.0
Norte         14.3  28.6  16.7   20.0
Sudeste       28.6  28.6   0.0   20.0
Sul           14.3  28.6  33.3   25.0

In [378]:
# USANDO OUTRAS FUNÇÕES DE AGREGAÇÃO 
pd.crosstab(df["regiao"], df["produto"])
pd.crosstab(df["regiao"], df["produto"],values=df["receita"], aggfunc="sum",
           margins=True, margins_name = "Receita Total" )

produto            A       B       C  Receita Total
regiao
Centro-Oeste   410.0     NaN   215.0            625
Nordeste         NaN   175.0   420.0            595
Norte          100.0   325.0   225.0            650
Sudeste        290.0   315.0     NaN            605
Sul            140.0   315.0   400.0            855
Receita Total  940.0  1130.0  1260.0           3330

In [379]:
pd.crosstab(
    df["regiao"],
    df["produto"],
    values=df["receita"], 
    aggfunc="sum",
    margins=True, 
    margins_name = "Receita Total" 
    ).round(2)
# ROUND serve para ARREDONDAR números decimais

produto            A       B       C  Receita Total
regiao
Centro-Oeste   410.0     NaN   215.0            625
Nordeste         NaN   175.0   420.0            595
Norte          100.0   325.0   225.0            650
Sudeste        290.0   315.0     NaN            605
Sul            140.0   315.0   400.0            855
Receita Total  940.0  1130.0  1260.0           3330

In [380]:
pd.crosstab(
    df["regiao"],
    df["produto"],
    values=df["receita"], 
    aggfunc="sum",
    normalize=True, 
    ).mul(100).round(1)
# MUL é multiplicação
# ROUND serve para ARREDONDAR números decimais

produto          A    B     C
regiao
Centro-Oeste  12.3  0.0   6.5
Nordeste       0.0  5.3  12.6
Norte          3.0  9.8   6.8
Sudeste        8.7  9.5   0.0
Sul            4.2  9.5  12.0

In [381]:
pd.crosstab(
    df["regiao"],
    df["produto"],
    values=df["receita"], 
    aggfunc="sum",
    normalize="index", 
    ).mul(100).round(1)
# as referêcias aqui são as linhas/ index
# INDEX = índice
# a numeração/identificador das linhas da tabela

produto          A     B     C
regiao
Centro-Oeste  65.6   0.0  34.4
Nordeste       0.0  29.4  70.6
Norte         15.4  50.0  34.6
Sudeste       47.9  52.1   0.0
Sul           16.4  36.8  46.8

In [382]:
pd.crosstab(
    df["regiao"],
    df["produto"],
    values=df["receita"], 
    aggfunc="sum",
    normalize="columns", 
    ).mul(100).round(1)

# A referência aqui são as COLUNAS/ COLUMNS

produto          A     B     C
regiao
Centro-Oeste  43.6   0.0  17.1
Nordeste       0.0  15.5  33.3
Norte         10.6  28.8  17.9
Sudeste       30.9  27.9   0.0
Sul           14.9  27.9  31.7

In [ ]:
# COMPARANDO COM O GROUPBY
pd.crosstab(df["regiao"], df["produto"])

produto       A  B  C
regiao
Centro-Oeste  3  0  1
Nordeste      0  1  2
Norte         1  2  1
Sudeste       2  2  0
Sul           1  2  2

In [384]:
# USANDO GROUPBY

# UNSTACK ( )
# unstack = desempilhar
# tirar informações que estão empilhadas nas linhas (índice) e transformar em colunas.
df.groupby(["regiao","produto"]).count().unstack().fillna(0).rename(columns={"receita":"vendas"})

             vendas
produto           A    B    C
regiao
Centro-Oeste    3.0  0.0  1.0
Nordeste        0.0  1.0  2.0
Norte           1.0  2.0  1.0
Sudeste         2.0  2.0  0.0
Sul             1.0  2.0  2.0

In [385]:
pd.crosstab(df["regiao"], df["produto"])

produto       A  B  C
regiao
Centro-Oeste  3  0  1
Nordeste      0  1  2
Norte         1  2  1
Sudeste       2  2  0
Sul           1  2  2