In [144]:
import pandas as pd
dados = pd.read_csv("dados.csv")

display(dados)

,order_id,cliente,data_pedido,fases,horas,taxas_horarias
0,1,Alpha Corp,2024-01,"['planejamento', 'desenvolvimento', 'teste']","[10, 50, 20]","[100, 150, 120]"
1,2,Beta Inc,2024-01,['planejamento'],[15],[110]
2,3,Gamma LLC,2024-02,"['desenvolvimento', 'teste']","[40, 25]","[140, 130]"
3,4,Delta Ltd,2024-02,"['planejamento', 'desenvolvimento']","[20, 30]","[100, 140]"
4,5,Epsilon SA,2024-03,"['planejamento', 'desenvolvimento', 'teste']","[30, 40, 20]","[120, 160, 110]"
5,6,Zeta Co,2024-03,"['planejamento', 'desenvolvimento', 'teste']","[10, 50, 20]","[100, 150, 120]"

In [145]:
# EXPLODE = explodir uma lista em várias linhas

dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        6 non-null      int64
 1   cliente         6 non-null      str
 2   data_pedido     6 non-null      str
 3   fases           6 non-null      str
 4   horas           6 non-null      str
 5   taxas_horarias  6 non-null      str
dtypes: int64(1), str(5)
memory usage: 420.0 bytes

In [146]:
dados.loc[0,"fases"]

"['planejamento', 'desenvolvimento', 'teste']"

In [147]:
type(dados.loc[0,"fases"])

str

In [148]:
for coluna in ["fases", "horas", "taxas_horarias"]:
    remover = ["[", "]", "'", " "]

    for simbolo in remover:
        dados[coluna] = dados[coluna].str.replace(simbolo, "")

    dados[coluna] = dados[coluna].str.split(",")

dados

,order_id,cliente,data_pedido,fases,horas,taxas_horarias
0,1,Alpha Corp,2024-01,"[planejamento, desenvolvimento, teste]","[10, 50, 20]","[100, 150, 120]"
1,2,Beta Inc,2024-01,[planejamento],[15],[110]
2,3,Gamma LLC,2024-02,"[desenvolvimento, teste]","[40, 25]","[140, 130]"
3,4,Delta Ltd,2024-02,"[planejamento, desenvolvimento]","[20, 30]","[100, 140]"
4,5,Epsilon SA,2024-03,"[planejamento, desenvolvimento, teste]","[30, 40, 20]","[120, 160, 110]"
5,6,Zeta Co,2024-03,"[planejamento, desenvolvimento, teste]","[10, 50, 20]","[100, 150, 120]"

In [149]:
dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        6 non-null      int64
 1   cliente         6 non-null      str
 2   data_pedido     6 non-null      str
 3   fases           6 non-null      object
 4   horas           6 non-null      object
 5   taxas_horarias  6 non-null      object
dtypes: int64(1), object(3), str(2)
memory usage: 420.0+ bytes

In [150]:
dados.loc[0, "fases"]

['planejamento', 'desenvolvimento', 'teste']

In [151]:
type(dados.loc[0,"fases"])

list

In [152]:
# USANDO O EXPLODE 

dados_expandido = dados.explode(["fases", "horas", "taxas_horarias"])

dados_expandido

   order_id     cliente data_pedido            fases horas taxas_horarias
0         1  Alpha Corp     2024-01     planejamento    10            100
0         1  Alpha Corp     2024-01  desenvolvimento    50            150
0         1  Alpha Corp     2024-01            teste    20            120
1         2    Beta Inc     2024-01     planejamento    15            110
2         3   Gamma LLC     2024-02  desenvolvimento    40            140
2         3   Gamma LLC     2024-02            teste    25            130
3         4   Delta Ltd     2024-02     planejamento    20            100
3         4   Delta Ltd     2024-02  desenvolvimento    30            140
4         5  Epsilon SA     2024-03     planejamento    30            120
4         5  Epsilon SA     2024-03  desenvolvimento    40            160
4         5  Epsilon SA     2024-03            teste    20            110
5         6     Zeta Co     2024-03     planejamento    10            100
5         6     Zeta Co     2024-03  desenvolvimento    50            150
5         6     Zeta Co     2024-03            teste    20            120

In [153]:
dados_expandido.info()

<class 'pandas.DataFrame'>
Index: 14 entries, 0 to 5
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        14 non-null     int64
 1   cliente         14 non-null     str
 2   data_pedido     14 non-null     str
 3   fases           14 non-null     str
 4   horas           14 non-null     str
 5   taxas_horarias  14 non-null     str
dtypes: int64(1), str(5)
memory usage: 784.0 bytes

In [154]:
dados_expandido["data_pedido"] = pd.to_datetime(dados_expandido["data_pedido"], format="%Y-%m")
dados_expandido

   order_id     cliente data_pedido            fases horas taxas_horarias
0         1  Alpha Corp  2024-01-01     planejamento    10            100
0         1  Alpha Corp  2024-01-01  desenvolvimento    50            150
0         1  Alpha Corp  2024-01-01            teste    20            120
1         2    Beta Inc  2024-01-01     planejamento    15            110
2         3   Gamma LLC  2024-02-01  desenvolvimento    40            140
2         3   Gamma LLC  2024-02-01            teste    25            130
3         4   Delta Ltd  2024-02-01     planejamento    20            100
3         4   Delta Ltd  2024-02-01  desenvolvimento    30            140
4         5  Epsilon SA  2024-03-01     planejamento    30            120
4         5  Epsilon SA  2024-03-01  desenvolvimento    40            160
4         5  Epsilon SA  2024-03-01            teste    20            110
5         6     Zeta Co  2024-03-01     planejamento    10            100
5         6     Zeta Co  2024-03-01  desenvolvimento    50            150
5         6     Zeta Co  2024-03-01            teste    20            120

In [155]:
dados_expandido.info()

<class 'pandas.DataFrame'>
Index: 14 entries, 0 to 5
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        14 non-null     int64
 1   cliente         14 non-null     str
 2   data_pedido     14 non-null     datetime64[us]
 3   fases           14 non-null     str
 4   horas           14 non-null     str
 5   taxas_horarias  14 non-null     str
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 784.0 bytes

In [156]:
for coluna in ["horas", "taxas_horarias"]:
    dados_expandido[coluna] = pd.to_numeric(dados_expandido[coluna])

dados_expandido

   order_id     cliente data_pedido            fases  horas  taxas_horarias
0         1  Alpha Corp  2024-01-01     planejamento     10             100
0         1  Alpha Corp  2024-01-01  desenvolvimento     50             150
0         1  Alpha Corp  2024-01-01            teste     20             120
1         2    Beta Inc  2024-01-01     planejamento     15             110
2         3   Gamma LLC  2024-02-01  desenvolvimento     40             140
2         3   Gamma LLC  2024-02-01            teste     25             130
3         4   Delta Ltd  2024-02-01     planejamento     20             100
3         4   Delta Ltd  2024-02-01  desenvolvimento     30             140
4         5  Epsilon SA  2024-03-01     planejamento     30             120
4         5  Epsilon SA  2024-03-01  desenvolvimento     40             160
4         5  Epsilon SA  2024-03-01            teste     20             110
5         6     Zeta Co  2024-03-01     planejamento     10             100
5         6     Zeta Co  2024-03-01  desenvolvimento     50             150
5         6     Zeta Co  2024-03-01            teste     20             120

In [157]:
dados_expandido.info()

<class 'pandas.DataFrame'>
Index: 14 entries, 0 to 5
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        14 non-null     int64
 1   cliente         14 non-null     str
 2   data_pedido     14 non-null     datetime64[us]
 3   fases           14 non-null     str
 4   horas           14 non-null     int64
 5   taxas_horarias  14 non-null     int64
dtypes: datetime64[us](1), int64(3), str(2)
memory usage: 784.0 bytes

In [158]:
# Total de horas por fase
dados_expandido.groupby("fases")["horas"].sum()

fases
desenvolvimento    210
planejamento        85
teste               85
Name: horas, dtype: int64

In [159]:
# TOTAL DE HORAS POR FASE POR MÊS

dados_expandido.groupby([dados_expandido["data_pedido"].dt.month, "fases"])["horas"].sum()

data_pedido  fases
1            desenvolvimento    50
             planejamento       25
             teste              20
2            desenvolvimento    70
             planejamento       20
             teste              25
3            desenvolvimento    90
             planejamento       40
             teste              40
Name: horas, dtype: int64