In [273]:
import pandas as pd

base = pd.read_csv("dados_transacoes (1).csv")

df = pd.read_csv("dados_transacoes (1).csv")

df.head()

,id_cliente,data_transacao,categoria_produto,idade,genero,preco,quantidade
0,702a8ab6-a2ff-4870-b32d-03870cb15afe,10/04/2024,Eletrônicos,56,Feminino,4052.46,2
1,e9f682e5-fb04-4a5a-9e89-2d289b236de2,30/04/2024,Eletrônicos,69,Feminino,1499.87,2
2,4d173947-ed0d-490f-af2d-bd18c5c79d4f,15/02/2024,Alimentos,46,Masculino,42.44,8
3,1c10a5b9-29b0-4c88-b861-83ea861c668a,21/02/2024,Roupas,32,Feminino,246.99,4
4,1ba015b7-28d0-4a24-8024-4895a4315874,16/04/2024,Roupas,60,Masculino,77.54,4

In [274]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 7 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   id_cliente         1000000 non-null  str
 1   data_transacao     1000000 non-null  str
 2   categoria_produto  1000000 non-null  str
 3   idade              1000000 non-null  int64
 4   genero             1000000 non-null  str
 5   preco              1000000 non-null  float64
 6   quantidade         1000000 non-null  int64
dtypes: float64(1), int64(2), str(4)
memory usage: 53.4 MB

In [275]:
df.describe()

                idade           preco      quantidade
count  1000000.000000  1000000.000000  1000000.000000
mean        44.001458      777.733227        2.300854
std         15.290201     1194.897497        1.936108
min         18.000000        5.000000        1.000000
25%         31.000000       46.120000        1.000000
50%         44.000000      181.940000        2.000000
75%         57.000000     1026.950000        3.000000
max         70.000000     5000.000000        9.000000

In [276]:
df.describe(exclude="number")

,id_cliente,data_transacao,categoria_produto,genero
count,1000000,1000000,1000000,1000000
unique,1000000,134,5,2
top,702a8ab6-a2ff-4870-b32d-03870cb15afe,06/05/2024,Alimentos,Masculino
freq,1,7712,200456,500002

In [277]:
df.groupby("categoria_produto")["preco"].mean()

categoria_produto
Alimentos           27.517138
Casa & Cozinha     850.503828
Eletrônicos       2747.807664
Livros             102.345245
Roupas             154.958499
Name: preco, dtype: float64

In [278]:
df.groupby(["categoria_produto", "genero"])["preco"].mean()

categoria_produto  genero
Alimentos          Feminino       27.553568
                   Masculino      27.480645
Casa & Cozinha     Feminino      849.994210
                   Masculino     851.016268
Eletrônicos        Feminino     2745.387879
                   Masculino    2750.215908
Livros             Feminino      102.312129
                   Masculino     102.378184
Roupas             Feminino      155.005536
                   Masculino     154.911331
Name: preco, dtype: float64

In [279]:
# %timeit serve para medir quanto tempo um código leva para executar.
# %timeit é muito usado para comparar performance no Pandas

#%timeit df.groupby("categoria_produto")["preco"].mean()
#%timeit df.groupby(["categoria_produto", "genero"])["preco"].mean()

In [280]:
df_otimizado = df.copy()
df_otimizado.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 7 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   id_cliente         1000000 non-null  str
 1   data_transacao     1000000 non-null  str
 2   categoria_produto  1000000 non-null  str
 3   idade              1000000 non-null  int64
 4   genero             1000000 non-null  str
 5   preco              1000000 non-null  float64
 6   quantidade         1000000 non-null  int64
dtypes: float64(1), int64(2), str(4)
memory usage: 53.4 MB

In [281]:
df_otimizado["data_transacao"] = pd.to_datetime(df_otimizado["data_transacao"],format="%d/%m/%Y")

df_otimizado.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 7 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   id_cliente         1000000 non-null  str
 1   data_transacao     1000000 non-null  datetime64[us]
 2   categoria_produto  1000000 non-null  str
 3   idade              1000000 non-null  int64
 4   genero             1000000 non-null  str
 5   preco              1000000 non-null  float64
 6   quantidade         1000000 non-null  int64
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 53.4 MB

In [282]:
df_otimizado.head()

,id_cliente,data_transacao,categoria_produto,idade,genero,preco,quantidade
0,702a8ab6-a2ff-4870-b32d-03870cb15afe,2024-04-10,Eletrônicos,56,Feminino,4052.46,2
1,e9f682e5-fb04-4a5a-9e89-2d289b236de2,2024-04-30,Eletrônicos,69,Feminino,1499.87,2
2,4d173947-ed0d-490f-af2d-bd18c5c79d4f,2024-02-15,Alimentos,46,Masculino,42.44,8
3,1c10a5b9-29b0-4c88-b861-83ea861c668a,2024-02-21,Roupas,32,Feminino,246.99,4
4,1ba015b7-28d0-4a24-8024-4895a4315874,2024-04-16,Roupas,60,Masculino,77.54,4

In [283]:
# informações por ano/year
df_otimizado["data_transacao"].dt.year

0         2024
1         2024
2         2024
3         2024
4         2024
          ...
999995    2024
999996    2024
999997    2024
999998    2024
999999    2024
Name: data_transacao, Length: 1000000, dtype: int32

In [284]:
# informações por mês/month
df_otimizado["data_transacao"].dt.month

0         4
1         4
2         2
3         2
4         4
         ..
999995    2
999996    4
999997    4
999998    4
999999    5
Name: data_transacao, Length: 1000000, dtype: int32

In [285]:
# informações por dia/ day
df_otimizado["data_transacao"].dt.day

0         10
1         30
2         15
3         21
4         16
          ..
999995    11
999996    11
999997    10
999998     7
999999     6
Name: data_transacao, Length: 1000000, dtype: int32

In [ ]:
# astype serve para alterar o tipo de dado de uma coluna.
# category é um tipo de dado do Pandas usado para colunas com valores repetidos / categorias fixas.

# Usando aqui o category ele mostra pra gente em textos mas armazena os dados como números, com isso diminuindo o armazenamento interno
df_otimizado["categoria_produto"]=df_otimizado["categoria_produto"].astype("category")
df_otimizado["genero"]=df_otimizado["genero"].astype("category")

df_otimizado.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 7 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   id_cliente         1000000 non-null  str
 1   data_transacao     1000000 non-null  datetime64[us]
 2   categoria_produto  1000000 non-null  category
 3   idade              1000000 non-null  int64
 4   genero             1000000 non-null  category
 5   preco              1000000 non-null  float64
 6   quantidade         1000000 non-null  int64
dtypes: category(2), datetime64[us](1), float64(1), int64(2), str(1)
memory usage: 40.1 MB

In [287]:
# sys ele permite interagir com o próprio sistema Python.
# Se você viu sys junto com Pandas, normalmente era para medir memória.

import sys 

sys.maxsize

9223372036854775807

In [288]:
sys.float_info.max

1.7976931348623157e+308

In [289]:
colunas_float = df_otimizado.select_dtypes(include="float64").columns
colunas_int = df_otimizado.select_dtypes(include="int64").columns

colunas_float,colunas_int

(Index(['preco'], dtype='str'), Index(['idade', 'quantidade'], dtype='str'))

In [290]:
df_otimizado[colunas_float] = df_otimizado[colunas_float].apply(pd.to_numeric,downcast="float")
df_otimizado[colunas_int] = df_otimizado[colunas_int].apply(pd.to_numeric,downcast="integer")

In [291]:
df_otimizado.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 7 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   id_cliente         1000000 non-null  str
 1   data_transacao     1000000 non-null  datetime64[us]
 2   categoria_produto  1000000 non-null  category
 3   idade              1000000 non-null  int8
 4   genero             1000000 non-null  category
 5   preco              1000000 non-null  float32
 6   quantidade         1000000 non-null  int8
dtypes: category(2), datetime64[us](1), float32(1), int8(2), str(1)
memory usage: 22.9 MB

In [292]:
df_otimizado.memory_usage()

Index                    132
id_cliente           8000000
data_transacao       8000000
categoria_produto    1000040
idade                1000000
genero               1000016
preco                4000000
quantidade           1000000
dtype: int64

In [293]:
df_otimizado.memory_usage().sum()

np.int64(24000188)

In [294]:
df_otimizado.memory_usage().sum() / df.memory_usage().sum()

np.float64(0.428573775504672)

In [ ]:
df_otimizado.describe()