##Criando dataframes com Pandas

In [198]:
import pandas as pd 

df_csv = pd.read_csv("cereal.csv")

df_csv.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843

In [199]:
df_csv.tail()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [200]:
df_excel = pd.read_excel("cereal.xlsx")
df_excel.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843

In [201]:
df_excel = pd.read_excel("cereal.xlsx")
df_excel.tail()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

##head() mostra as 5 primeiras linhas 

##tail() mostra as 5 últimas linhas

##A partir da área de transferência

In [202]:
df_transferencia = pd.read_clipboard()  # clipboard pega a parte selecionada do excel 

df_transferencia

,df_funcionarios_completo,=,"pd.merge(df_funcionarios,","df_dados_funcionarios,","on=""id"")"
0,df_funcionarios_completo,NaN,NaN,NaN,NaN

##A partir de um dicionário

In [203]:
funcionarios = {
    "Nome": ["João Silva", "Maria Souza", "José Ramos", "Pedro Ferreira"], 
    "Idade": [35,40,54,39],
    "Tempo de Empresa":[3,10,15,7],
}

In [204]:
df_dicionario = pd.DataFrame(funcionarios)

df_dicionario

             Nome  Idade  Tempo de Empresa
0      João Silva     35                 3
1     Maria Souza     40                10
2      José Ramos     54                15
3  Pedro Ferreira     39                 7

##Combinando linhas de diferentes dataframes

In [205]:
mais_funcionarios = {
    "Nome":["Paula Lima", "Marta Nunes"],
    "Idade":[28,45],
    "Tempo de Empresa": [5,12],
}

In [206]:
mais_funcionarios

{'Nome': ['Paula Lima', 'Marta Nunes'],
 'Idade': [28, 45],
 'Tempo de Empresa': [5, 12]}

In [207]:
df_mais_funcionarios = pd.DataFrame(mais_funcionarios)

df_mais_funcionarios

          Nome  Idade  Tempo de Empresa
0   Paula Lima     28                 5
1  Marta Nunes     45                12

##Concat é concatenar/juntar

In [208]:
df_funcionarios = pd.concat([df_dicionario, df_mais_funcionarios],ignore_index=True)

df_funcionarios

             Nome  Idade  Tempo de Empresa
0      João Silva     35                 3
1     Maria Souza     40                10
2      José Ramos     54                15
3  Pedro Ferreira     39                 7
4      Paula Lima     28                 5
5     Marta Nunes     45                12

##Combinando colunas de diferentes dataframes

In [209]:
import numpy as np 

setores = ["Vendas", "RH", "TI"]

dados_funcionarios = {
    "Setor": np.random.choice(setores,6),   #random siginifica aleatório no Pandas
    "Salario": np.random.randint(2000,10000,6) #randint siginifica números inteiros no Pandas
}

df_dados_funcionarios = pd.DataFrame(dados_funcionarios)
df_dados_funcionarios

    Setor  Salario
0  Vendas     4642
1      RH     7779
2  Vendas     6962
3  Vendas     9181
4      TI     7583
5      TI     7740

In [210]:
df_funcionarios_completo = pd.concat([df_funcionarios, df_dados_funcionarios],axis="columns")

df_funcionarios_completo

             Nome  Idade  Tempo de Empresa   Setor  Salario
0      João Silva     35                 3  Vendas     4642
1     Maria Souza     40                10      RH     7779
2      José Ramos     54                15  Vendas     6962
3  Pedro Ferreira     39                 7  Vendas     9181
4      Paula Lima     28                 5      TI     7583
5     Marta Nunes     45                12      TI     7740

##Juntando dataframes com merge ()

##merge() no Pandas é usado para juntar tabelas, parecido com JOIN no SQL.

In [211]:
funcionarios ={
    "id":["FTI1", "FVE2", "FRH1", "FVE1"],
    "Nome": ["João Silva", "Maria Souza", "José Ramos", "Pedro Ferreira"],
    "Idade": [35,40,54,39],
    "Tempo de Empresa": [3,10,15,7]
}

df2_funcionarios = pd.DataFrame(funcionarios)
df2_funcionarios

     id            Nome  Idade  Tempo de Empresa
0  FTI1      João Silva     35                 3
1  FVE2     Maria Souza     40                10
2  FRH1      José Ramos     54                15
3  FVE1  Pedro Ferreira     39                 7

In [212]:
dados_funcionarios = {
    "id": ["FVE1", "FRH1", "FTI1", "FVE2"],
    "Setor": ["Vendas", "RH", "TI", "Vendas"],
    "Salario": np.random.randint(2000,10000,size=4),
}

df2_dados_funcionarios = pd.DataFrame(dados_funcionarios)
df2_dados_funcionarios

     id   Setor  Salario
0  FVE1  Vendas     4536
1  FRH1      RH     3891
2  FTI1      TI     9436
3  FVE2  Vendas     3418

In [214]:
df2_funcionarios_completo = pd.merge(df2_funcionarios, df2_dados_funcionarios, on="id")

df2_funcionarios_completo

     id            Nome  Idade  Tempo de Empresa   Setor  Salario
0  FTI1      João Silva     35                 3      TI     9436
1  FVE2     Maria Souza     40                10  Vendas     3418
2  FRH1      José Ramos     54                15      RH     3891
3  FVE1  Pedro Ferreira     39                 7  Vendas     4536