In [31]:
import pandas as pd
import numpy  as nd 

df_vendas = pd.read_csv("vendas_tech.csv", sep =",")
display(df_vendas)
df_gerentes = pd.read_excel("gerentes_lojas.xlsx")
display(df_gerentes)

C:\Users\User\AppData\Local\Temp\ipykernel_9772\3455816229.py:4: DtypeWarning: Columns (0: Data_Base) have mixed types. Specify dtype option on import or set low_memory=False.
  df_vendas = pd.read_csv("vendas_tech.csv", sep =",")

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

In [32]:
# tratamento de dados
# display(df_vendas["Loja"])
# display(df_vendas[["Loja", "Cliente"]])


#colunas 
df_analise = df_vendas.drop(columns = ["Data_Base"]) 
# usamos o drop para apagar/deletar uma coluna que aqui foi a "Data_Base"


# nulos  
# df_analise = df_analise.dropna()  
# # dropna excluir todas as linhas que têm um valor vazio 
#fillna preenche os valores vazios 
df_analise["Loja"] = df_analise["Loja"].fillna("Onlinne")  


# tipos de dados
#datetime é transformar em datas  
df_analise["DataFormatada"] = pd.to_datetime(df_analise["Data"], format="%Y-%m-%d") 
# padronização 
# str disponibiliza as funções de texto dentro do Python # strip que remove espaços duplicados
# title é usado para padronizar as primeiras letras de cada palavra em maiúsculo e o resto em minusclo
df_analise["Loja"] = df_analise["Loja"].str.strip()
df_analise["Loja"] = df_analise["Loja"].str.title()  


# duplicatas remover linhas iguais 
df_analise = df_analise.drop_duplicates(subset=["ID_Pedido"]) 
# duplicates()remove os duplicados 
# subset= ele permite selecionar uma lista de colunas específica que quiser para sair os duplicados.
# keep= é manter, você vai definir se vai manter o primeiro (first) ou o último (last) valor duplicado, se não passar nada ele mantém sempre o PRIMEIRO VALOR.

display(df_analise)
display(df_analise.info())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,DataFormatada
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2023-06-08
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,2023-03-01
2,3,2023-02-25,Onlinne,"Monitor 27""",1200.0,1,Cliente_14859,2023-02-25
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,2024-11-19
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2024-01-27
...,...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732,2023-01-24
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058,2024-08-28
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864,2024-03-18
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205,2023-11-04
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237,2024-06-15

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100000 non-null  int64
 1   Data            100000 non-null  str
 2   Loja            100000 non-null  str
 3   Produto         100000 non-null  str
 4   Preco_Unitario  100000 non-null  float64
 5   Qtd             100000 non-null  int64
 6   Cliente         100000 non-null  str
 7   DataFormatada   100000 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(2), str(4)
memory usage: 6.1 MB

None

In [33]:
# criar novas colunas 


# faturamento 
df_analise["Faturamento"] = df_analise["Qtd"] * df_analise["Preco_Unitario"]

# regiao
# unique são os valores únicos dentro da tabela
display(df_analise["Loja"].unique()) 

def definir_regiao(loja):
    dic_regioes = {
        "São Paulo": "Sudeste", 
        "Belo Horizonte": "Sudeste",   
        "Online": "Online", 
        "Rio de Janeiro": "Sudeste",
        "Salvador": "Nordeste",         
        "Recife": "Nordeste",      
        "Curitiba": "Sul",   
        "Porto Alegre": "Sul"          
    }  
    
    return dic_regioes.get(loja)

df_analise["Região"] = df_analise["Loja"].map(definir_regiao)



# forma de venda 
import numpy as np
df_analise["Forma_de_Venda"] = np.where(df_analise["Loja"]== "Onlinne", "Online", "Presencial")  
# np.where é uma condição 


display(df_analise)

<StringArray>
[     'São Paulo', 'Belo Horizonte',        'Onlinne', 'Rio De Janeiro',
       'Salvador',         'Recife',       'Curitiba',   'Porto Alegre']
Length: 8, dtype: str

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,DataFormatada,Faturamento,Região,Forma_de_Venda
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2023-06-08,120.0,Sudeste,Presencial
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,2023-03-01,5500.0,Sudeste,Presencial
2,3,2023-02-25,Onlinne,"Monitor 27""",1200.0,1,Cliente_14859,2023-02-25,1200.0,NaN,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,2024-11-19,240.0,NaN,Presencial
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2024-01-27,2200.0,NaN,Presencial
...,...,...,...,...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732,2023-01-24,240.0,Sudeste,Presencial
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058,2024-08-28,40.0,NaN,Presencial
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864,2024-03-18,4400.0,Sul,Presencial
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205,2023-11-04,5500.0,Sul,Presencial
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237,2024-06-15,250.0,Sul,Presencial

In [39]:
# analisar usando filtros/ como filtrar a base de dados

df_analise = df_analise.sort_values(by = "Data")  # ordenando a tabela em data 

# .loc localiza por nome da coluna e por nome da linha que é o índice
# Exemplo usando o .loc : id do pedido
id_pedido = 4 
loja = df_analise.loc[df_analise["ID_Pedido"]==4,"Loja"]         # .loc[indice, coluna]
produto = df_analise.loc[df_analise["ID_Pedido"]==4, "Produto"]  # .loc[indice, coluna]      
cliente = df_analise.loc[df_analise["ID_Pedido"]==4, "Cliente"]  # .loc[indice, coluna]
print(loja,produto, cliente)            # coloca o print paa mostrar as 3 informações de cima 


# .iloc localiza por posição 
# Exemplo usando .iloc 
id_pedido = 4 
loja = df_analise.iloc[3,2]        #.iloc[linha, coluna]
produto = df_analise.iloc[3,3]        # .iloc[linha, coluna]
cliente = df_analise.iloc [3,6]       # .iloc[linha, coluna]
print(loja, produto, cliente)

# condicional pode passar por regra de linha ou uma linha inteira
df_id_pedido_4 = df_analise[df_analise["ID_Pedido"]==4] # aqui passou a condição 


# exportar pedaços da base 
df_vendas_sp = df_analise[df_analise["Loja"]=="São Paulo"]
display(df_vendas_sp)

# exportar as vendas de 2024  
df_analise["Data"] = pd.to_datetime(df_analise["Data"])  
df_vendas_2024 = df_analise[df_analise["Data"].dt.year==2024]
display(df_vendas_2024)  # mostra as vendas apenas de 2024

# duplas condições 
condicao = df_analise["Produto"]=="Cabo HDMI"
condicao2 = df_analise["Região"]=="Sul"
df_vendas_HDMI_SUL = df_analise[condicao & condicao2]
display(df_vendas_HDMI_SUL)

3    Rio De Janeiro
Name: Loja, dtype: str 3    Mouse Gamer
Name: Produto, dtype: str 3    Cliente_17343
Name: Cliente, dtype: str
Salvador Cabo HDMI Cliente_1746

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,DataFormatada,Faturamento,Região,Forma_de_Venda
62582,62583,2023-01-01,São Paulo,Notebook HP,3200.0,1,Cliente_16151,2023-01-01,3200.0,Sudeste,Presencial
47464,47465,2023-01-01,São Paulo,iPhone 14,5500.0,3,Cliente_7589,2023-01-01,16500.0,Sudeste,Presencial
65753,65754,2023-01-01,São Paulo,iPhone 14,5500.0,1,Cliente_10437,2023-01-01,5500.0,Sudeste,Presencial
13089,13090,2023-01-01,São Paulo,Notebook Dell,3500.0,1,Cliente_9087,2023-01-01,3500.0,Sudeste,Presencial
41070,41071,2023-01-01,São Paulo,Teclado Mecânico,250.0,2,Cliente_11176,2023-01-01,500.0,Sudeste,Presencial
...,...,...,...,...,...,...,...,...,...,...,...
86854,86855,2024-12-30,São Paulo,Teclado Mecânico,250.0,2,Cliente_5097,2024-12-30,500.0,Sudeste,Presencial
7445,7446,2024-12-30,São Paulo,iPhone 14,5500.0,1,Cliente_1302,2024-12-30,5500.0,Sudeste,Presencial
38478,38479,2024-12-30,São Paulo,Smartphone Samsung,2200.0,1,Cliente_13360,2024-12-30,2200.0,Sudeste,Presencial
176,177,2024-12-30,São Paulo,Smartphone Samsung,2200.0,3,Cliente_4388,2024-12-30,6600.0,Sudeste,Presencial
91692,91693,2024-12-30,São Paulo,iPhone 14,5500.0,1,Cliente_17362,2024-12-30,5500.0,Sudeste,Presencial

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,DataFormatada,Faturamento,Região,Forma_de_Venda
68139,68140,2024-01-01,São Paulo,iPhone 14,5500.0,1,Cliente_11112,2024-01-01,5500.0,Sudeste,Presencial
43104,43105,2024-01-01,Belo Horizonte,"Monitor 27""",1200.0,1,Cliente_3307,2024-01-01,1200.0,Sudeste,Presencial
54221,54222,2024-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_2708,2024-01-01,40.0,Sul,Presencial
69242,69243,2024-01-01,Belo Horizonte,Teclado Mecânico,250.0,1,Cliente_15377,2024-01-01,250.0,Sudeste,Presencial
97744,97745,2024-01-01,Salvador,Smartphone Samsung,2200.0,5,Cliente_23791,2024-01-01,11000.0,Nordeste,Presencial
...,...,...,...,...,...,...,...,...,...,...,...
77400,77401,2024-12-30,Curitiba,Teclado Mecânico,250.0,1,Cliente_7243,2024-12-30,250.0,Sul,Presencial
54844,54845,2024-12-30,Curitiba,Mouse Gamer,120.0,1,Cliente_17215,2024-12-30,120.0,Sul,Presencial
74279,74280,2024-12-30,Rio De Janeiro,Cabo HDMI,40.0,5,Cliente_15432,2024-12-30,200.0,NaN,Presencial
19828,19829,2024-12-30,Salvador,Notebook Dell,3500.0,1,Cliente_25627,2024-12-30,3500.0,Nordeste,Presencial
91692,91693,2024-12-30,São Paulo,iPhone 14,5500.0,1,Cliente_17362,2024-12-30,5500.0,Sudeste,Presencial

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,DataFormatada,Faturamento,Região,Forma_de_Venda
42050,42051,2023-01-01,Curitiba,Cabo HDMI,40.0,10,Cliente_16622,2023-01-01,400.0,Sul,Presencial
1699,1700,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_14435,2023-01-01,40.0,Sul,Presencial
35598,35599,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_18680,2023-01-01,40.0,Sul,Presencial
49139,49140,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_24445,2023-01-01,40.0,Sul,Presencial
37129,37130,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_22886,2023-01-01,40.0,Sul,Presencial
...,...,...,...,...,...,...,...,...,...,...,...
78583,78584,2024-12-30,Curitiba,Cabo HDMI,40.0,1,Cliente_21307,2024-12-30,40.0,Sul,Presencial
64472,64473,2024-12-30,Porto Alegre,Cabo HDMI,40.0,2,Cliente_11598,2024-12-30,80.0,Sul,Presencial
35126,35127,2024-12-30,Curitiba,Cabo HDMI,40.0,2,Cliente_20687,2024-12-30,80.0,Sul,Presencial
47773,47774,2024-12-30,Porto Alegre,Cabo HDMI,40.0,2,Cliente_14363,2024-12-30,80.0,Sul,Presencial
75694,75695,2024-12-30,Porto Alegre,Cabo HDMI,40.0,1,Cliente_29587,2024-12-30,40.0,Sul,Presencial

In [49]:
# analisar por agrupamento
display(df_analise)

analise_lojas = df_analise[["Loja","Faturamento"]].groupby("Loja").sum()  # groupby agrupa uma coluna do banco de dados
display(analise_lojas)

# ranking de produtos que mais venderam no online
df_vendas_onlinne = df_analise[df_analise["Loja"]=="Onlinne"]
analise_produtos_onlinne = df_vendas_onlinne[["Produto", "Qtd"]].groupby("Produto").sum()
analise_produtos_onlinne = analise_produtos_onlinne.sort_values(by="Qtd", ascending=False)
analise_produtos_onlinne = analise_produtos_onlinne.rename(columns={"Qtd": "Vendas Totais"}) # alterando o nome da coluna Qtd para Vendas Totais 
display(analise_produtos_onlinne)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,DataFormatada,Faturamento,Região,Forma_de_Venda
34749,34750,2023-01-01,Rio De Janeiro,Notebook HP,3200.0,1,Cliente_9014,2023-01-01,3200.0,NaN,Presencial
61282,61283,2023-01-01,Curitiba,iPhone 14,5500.0,1,Cliente_2096,2023-01-01,5500.0,Sul,Presencial
62582,62583,2023-01-01,São Paulo,Notebook HP,3200.0,1,Cliente_16151,2023-01-01,3200.0,Sudeste,Presencial
91764,91765,2023-01-01,Salvador,Cabo HDMI,40.0,1,Cliente_1746,2023-01-01,40.0,Nordeste,Presencial
30885,30886,2023-01-01,Porto Alegre,Teclado Mecânico,250.0,1,Cliente_10039,2023-01-01,250.0,Sul,Presencial
...,...,...,...,...,...,...,...,...,...,...,...
77400,77401,2024-12-30,Curitiba,Teclado Mecânico,250.0,1,Cliente_7243,2024-12-30,250.0,Sul,Presencial
54844,54845,2024-12-30,Curitiba,Mouse Gamer,120.0,1,Cliente_17215,2024-12-30,120.0,Sul,Presencial
74279,74280,2024-12-30,Rio De Janeiro,Cabo HDMI,40.0,5,Cliente_15432,2024-12-30,200.0,NaN,Presencial
19828,19829,2024-12-30,Salvador,Notebook Dell,3500.0,1,Cliente_25627,2024-12-30,3500.0,Nordeste,Presencial
91692,91693,2024-12-30,São Paulo,iPhone 14,5500.0,1,Cliente_17362,2024-12-30,5500.0,Sudeste,Presencial

                Faturamento
Loja
Belo Horizonte   41714890.0
Curitiba         41121720.0
Onlinne           6080850.0
Porto Alegre     41678460.0
Recife           42190390.0
Rio De Janeiro   42294720.0
Salvador         42300610.0
São Paulo        42090690.0

                    Vendas Totais
Produto
Notebook HP                   442
Cabo HDMI                     403
iPhone 14                     390
Mouse Gamer                   379
Notebook Dell                 369
Teclado Mecânico              343
Monitor 27"                   332
Smartphone Samsung            311